// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using МаршрутСборки.Data;

#nullable disable

namespace МаршрутСборки.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615200423_AddAssemblyShippedDate")]
    partial class AddAssemblyShippedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("МаршрутСборки.Models.Assembly", b =>
                {
                    b.Property<int>("AssemblyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssemblyId"));

                    b.Property<int?>("AssemblerId")
                        .HasColumnType("integer");

                    b.Property<string>("AssemblyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Configuration")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DispatcherId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AssemblyId");

                    b.HasIndex("AssemblerId");

                    b.HasIndex("DispatcherId");

                    b.ToTable("Assemblies");
                });

            modelBuilder.Entity("МаршрутСборки.Models.AssemblyComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssemblyId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("AssemblyId", "ComponentId")
                        .IsUnique();

                    b.ToTable("AssemblyComponents");
                });

            modelBuilder.Entity("МаршрутСборки.Models.AssemblyReworkItem", b =>
                {
                    b.Property<int>("ReworkItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReworkItemId"));

                    b.Property<int>("AssemblyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsIssued")
                        .HasColumnType("boolean");

                    b.Property<int>("NewComponentId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("OldComponentId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ReworkItemId");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("NewComponentId");

                    b.HasIndex("OldComponentId");

                    b.ToTable("AssemblyReworkItems");
                });

            modelBuilder.Entity("МаршрутСборки.Models.Component", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinStock")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockBalance")
                        .HasColumnType("integer");

                    b.HasKey("ComponentId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            ComponentId = 1,
                            Category = "Процессор",
                            MinStock = 3,
                            Name = "Процессор Intel Core i3-12100",
                            Price = 12500m,
                            SKU = "CPU-I3-12100",
                            StockBalance = 15
                        },
                        new
                        {
                            ComponentId = 2,
                            Category = "Процессор",
                            MinStock = 3,
                            Name = "Процессор Intel Core i5-12400",
                            Price = 18900m,
                            SKU = "CPU-I5-12400",
                            StockBalance = 10
                        },
                        new
                        {
                            ComponentId = 3,
                            Category = "Процессор",
                            MinStock = 2,
                            Name = "Процессор Intel Core i5-14400",
                            Price = 22500m,
                            SKU = "CPU-I5-14400",
                            StockBalance = 8
                        },
                        new
                        {
                            ComponentId = 4,
                            Category = "Процессор",
                            MinStock = 2,
                            Name = "Процессор Intel Core i7-13700",
                            Price = 31000m,
                            SKU = "CPU-I7-13700",
                            StockBalance = 5
                        },
                        new
                        {
                            ComponentId = 5,
                            Category = "Оперативная память",
                            MinStock = 5,
                            Name = "ОЗУ 8 GB DDR5",
                            Price = 4200m,
                            SKU = "RAM-8GB-DDR5",
                            StockBalance = 30
                        },
                        new
                        {
                            ComponentId = 6,
                            Category = "Оперативная память",
                            MinStock = 5,
                            Name = "ОЗУ 16 GB DDR5",
                            Price = 7800m,
                            SKU = "RAM-16GB-DDR5",
                            StockBalance = 25
                        },
                        new
                        {
                            ComponentId = 7,
                            Category = "Оперативная память",
                            MinStock = 3,
                            Name = "ОЗУ 32 GB DDR5",
                            Price = 14500m,
                            SKU = "RAM-32GB-DDR5",
                            StockBalance = 12
                        },
                        new
                        {
                            ComponentId = 8,
                            Category = "Накопитель",
                            MinStock = 10,
                            Name = "SSD накопитель 512 GB",
                            Price = 5500m,
                            SKU = "SSD-512GB",
                            StockBalance = 40
                        },
                        new
                        {
                            ComponentId = 9,
                            Category = "Накопитель",
                            MinStock = 5,
                            Name = "SSD накопитель 1 TB",
                            Price = 9200m,
                            SKU = "SSD-1TB",
                            StockBalance = 20
                        },
                        new
                        {
                            ComponentId = 10,
                            Category = "Видеокарта",
                            MinStock = 2,
                            Name = "Видеокарта RTX 3050 8GB",
                            Price = 24000m,
                            SKU = "GPU-RTX3050",
                            StockBalance = 6
                        },
                        new
                        {
                            ComponentId = 11,
                            Category = "Видеокарта",
                            MinStock = 2,
                            Name = "Видеокарта RTX 5060 8GB",
                            Price = 38000m,
                            SKU = "GPU-RTX5060",
                            StockBalance = 4
                        },
                        new
                        {
                            ComponentId = 12,
                            Category = "Блок питания",
                            MinStock = 4,
                            Name = "Блок питания 600W APFC",
                            Price = 6800m,
                            SKU = "PSU-600W",
                            StockBalance = 18
                        },
                        new
                        {
                            ComponentId = 13,
                            Category = "Блок питания",
                            MinStock = 3,
                            Name = "Блок питания 700W APFC",
                            Price = 8500m,
                            SKU = "PSU-700W",
                            StockBalance = 10
                        },
                        new
                        {
                            ComponentId = 14,
                            Category = "Корпус",
                            MinStock = 5,
                            Name = "Корпус NITRINOnet",
                            Price = 4500m,
                            SKU = "CASE-NITRINO",
                            StockBalance = 22
                        },
                        new
                        {
                            ComponentId = 15,
                            Category = "Материнская плата",
                            MinStock = 2,
                            Name = "Материнская плата ASUS Z690",
                            Price = 18200m,
                            SKU = "MB-Z690",
                            StockBalance = 8
                        },
                        new
                        {
                            ComponentId = 16,
                            Category = "Корпус",
                            MinStock = 3,
                            Name = "Корпус NITRINOnet S600 (системный блок)",
                            Price = 8900m,
                            SKU = "CASE-S600",
                            StockBalance = 15
                        },
                        new
                        {
                            ComponentId = 17,
                            Category = "Корпус",
                            MinStock = 2,
                            Name = "Корпус NITRINOnet S600M (моноблок)",
                            Price = 14500m,
                            SKU = "CASE-S600M",
                            StockBalance = 8
                        },
                        new
                        {
                            ComponentId = 18,
                            Category = "Монитор",
                            MinStock = 2,
                            Name = "Монитор 22\" Full HD",
                            Price = 18850m,
                            SKU = "MON-22",
                            StockBalance = 10
                        },
                        new
                        {
                            ComponentId = 19,
                            Category = "Периферия",
                            MinStock = 5,
                            Name = "Клавиатура НЬЮКЛИК (PREMIUM)",
                            Price = 2800m,
                            SKU = "KB-NEWCLICK",
                            StockBalance = 20
                        },
                        new
                        {
                            ComponentId = 20,
                            Category = "Периферия",
                            MinStock = 5,
                            Name = "Мышь НЬЮКЛИК (PREMIUM)",
                            Price = 1950m,
                            SKU = "MS-NEWCLICK",
                            StockBalance = 0
                        });
                });

            modelBuilder.Entity("МаршрутСборки.Models.EventLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("МаршрутСборки.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Администратор"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Диспетчер"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Сборщик"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Кладовщик"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Тестировщик"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "Гарантийный инженер"
                        });
                });

            modelBuilder.Entity("МаршрутСборки.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestId"));

                    b.Property<int>("AssemblyId")
                        .HasColumnType("integer");

                    b.Property<string>("Defects")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TesterId")
                        .HasColumnType("integer");

                    b.HasKey("TestId");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("TesterId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("МаршрутСборки.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FirstName = "Системный",
                            IsActive = true,
                            LastName = "Администратор",
                            Login = "admin",
                            PasswordHash = "$2a$11$9g1kDJ2.cg3jsIOUbMif6eJT5XldVmhavbM4XL96xwGzUc48FlP46",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            FirstName = "Иван",
                            IsActive = true,
                            LastName = "Иванов",
                            Login = "ivanov",
                            PasswordHash = "$2a$11$7pHooEzSreJMLtBtt8mJPOWi20fIZm.64pDbHaAmYAQKOJNRrcdru",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 3,
                            FirstName = "Пётр",
                            IsActive = true,
                            LastName = "Петров",
                            Login = "petrov",
                            PasswordHash = "$2a$11$DBaLoqjmbMeUJW046Hyfy.gcPWO9Sz8AIIBWJK.swldbMYifVrRJm",
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 4,
                            FirstName = "Алексей",
                            IsActive = true,
                            LastName = "Сидоров",
                            Login = "sidorov",
                            PasswordHash = "$2a$11$l2f9V2k2HLYFkV1rpYXNye0H6XcMrJQk6M/kDr1EmkTypwy6ZDzZK",
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 5,
                            FirstName = "Михаил",
                            IsActive = true,
                            LastName = "Фёдоров",
                            Login = "fedorov",
                            PasswordHash = "$2a$11$2Ic0OhDv8Ad2CgkGMWsYIuM3zPIEd9IIdhuFWhBAciQkYMs.hkSvW",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            FirstName = "Сергей",
                            IsActive = true,
                            LastName = "Алексеев",
                            Login = "alekseev",
                            PasswordHash = "$2a$11$pVna6URry9fOwAXwdrtDl.WRvanlmMD3DGFkDEzFyMCGtWdjRkxsK",
                            RoleId = 6
                        });
                });

            modelBuilder.Entity("МаршрутСборки.Models.WarehouseOperation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperationId"));

                    b.Property<int?>("AssemblyId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentRef")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("OperationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OperationId");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("UserId");

                    b.ToTable("WarehouseOperations");
                });

            modelBuilder.Entity("МаршрутСборки.Models.WarrantyCase", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CaseId"));

                    b.Property<int?>("AssemblyId")
                        .HasColumnType("integer");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EngineerId")
                        .HasColumnType("integer");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepairNotes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CaseId");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("EngineerId");

                    b.ToTable("WarrantyCases");
                });

            modelBuilder.Entity("МаршрутСборки.Models.WarrantyCaseNote", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NoteId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NoteId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CaseId");

                    b.ToTable("WarrantyCaseNotes");
                });

            modelBuilder.Entity("МаршрутСборки.Models.Assembly", b =>
                {
                    b.HasOne("МаршрутСборки.Models.User", "Assembler")
                        .WithMany("AssignedAssemblies")
                        .HasForeignKey("AssemblerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("МаршрутСборки.Models.User", "Dispatcher")
                        .WithMany("CreatedAssemblies")
                        .HasForeignKey("DispatcherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assembler");

                    b.Navigation("Dispatcher");
                });

            modelBuilder.Entity("МаршрутСборки.Models.AssemblyComponent", b =>
                {
                    b.HasOne("МаршрутСборки.Models.Assembly", "Assembly")
                        .WithMany("AssemblyComponents")
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("МаршрутСборки.Models.Component", "Component")
                        .WithMany("AssemblyComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assembly");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("МаршрутСборки.Models.AssemblyReworkItem", b =>
                {
                    b.HasOne("МаршрутСборки.Models.Assembly", "Assembly")
                        .WithMany()
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("МаршрутСборки.Models.Component", "NewComponent")
                        .WithMany()
                        .HasForeignKey("NewComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("МаршрутСборки.Models.Component", "OldComponent")
                        .WithMany()
                        .HasForeignKey("OldComponentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assembly");

                    b.Navigation("NewComponent");

                    b.Navigation("OldComponent");
                });

            modelBuilder.Entity("МаршрутСборки.Models.EventLog", b =>
                {
                    b.HasOne("МаршрутСборки.Models.User", "User")
                        .WithMany("EventLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("МаршрутСборки.Models.Test", b =>
                {
                    b.HasOne("МаршрутСборки.Models.Assembly", "Assembly")
                        .WithMany("Tests")
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("МаршрутСборки.Models.User", "Tester")
                        .WithMany("Tests")
                        .HasForeignKey("TesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assembly");

                    b.Navigation("Tester");
                });

            modelBuilder.Entity("МаршрутСборки.Models.User", b =>
                {
                    b.HasOne("МаршрутСборки.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("МаршрутСборки.Models.WarehouseOperation", b =>
                {
                    b.HasOne("МаршрутСборки.Models.Assembly", "Assembly")
                        .WithMany("WarehouseOperations")
                        .HasForeignKey("AssemblyId");

                    b.HasOne("МаршрутСборки.Models.Component", "Component")
                        .WithMany("WarehouseOperations")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("МаршрутСборки.Models.User", "User")
                        .WithMany("WarehouseOperations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assembly");

                    b.Navigation("Component");

                    b.Navigation("User");
                });

            modelBuilder.Entity("МаршрутСборки.Models.WarrantyCase", b =>
                {
                    b.HasOne("МаршрутСборки.Models.Assembly", "Assembly")
                        .WithMany("WarrantyCases")
                        .HasForeignKey("AssemblyId");

                    b.HasOne("МаршрутСборки.Models.User", "Engineer")
                        .WithMany("WarrantyCases")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assembly");

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("МаршрутСборки.Models.WarrantyCaseNote", b =>
                {
                    b.HasOne("МаршрутСборки.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("МаршрутСборки.Models.WarrantyCase", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("МаршрутСборки.Models.Assembly", b =>
                {
                    b.Navigation("AssemblyComponents");

                    b.Navigation("Tests");

                    b.Navigation("WarehouseOperations");

                    b.Navigation("WarrantyCases");
                });

            modelBuilder.Entity("МаршрутСборки.Models.Component", b =>
                {
                    b.Navigation("AssemblyComponents");

                    b.Navigation("WarehouseOperations");
                });

            modelBuilder.Entity("МаршрутСборки.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("МаршрутСборки.Models.User", b =>
                {
                    b.Navigation("AssignedAssemblies");

                    b.Navigation("CreatedAssemblies");

                    b.Navigation("EventLogs");

                    b.Navigation("Tests");

                    b.Navigation("WarehouseOperations");

                    b.Navigation("WarrantyCases");
                });
#pragma warning restore 612, 618
        }
    }
}
